### ISSUE TITLE
NPE handling large multipart upload

### ISSUE THREAD

**Issue by mfikes** [juxt/yada#74] opened 2016-03-12 04:04 UTC
An NPE will occur in `yada.multipart/finish-up` if you upload a large file to a Yada-based server.

To repro on OS X, clone the `yada` repo and start up `lein repl` in its top level directory. Then

```clojure
(require '[aleph.http :refer [start-server]]
         '[bidi.ring :refer [make-handler]]
         '[yada.yada :refer [resource]])
```

and

```
(start-server
  (make-handler
    ["/upload"
     (resource
       {:methods
        {:post
         {:consumes "multipart/form-data"
          :response (constantly nil)}}})])
  {:port 3000})
```

Then create a large file:

```
dd if=/dev/zero of=file.txt count=1024 bs=1024
```

and use cURL to upload the file to the server:

```
curl -F file=@file.txt http://localhost:3000/upload
```

You should get an error:

```
20:02:42.021 [manifold-pool-2-7] ERROR yada.multipart - Failed: null
java.lang.NullPointerException: null
	at clojure.lang.Numbers.ops(Numbers.java:1013)
	at clojure.lang.Numbers.add(Numbers.java:128)
	at yada.multipart$finish_up.invoke(multipart.clj:313)
	at yada.multipart$process_chunk.invoke(multipart.clj:334)
	at yada.multipart$parse_multipart$this__2646__auto____24204$fn__24205$fn__24206.invoke(multipart.clj:420)
	at manifold.deferred$eval2555$chain___2576.invoke(deferred.clj:860)
	at yada.multipart$parse_multipart$this__2646__auto____24204$fn__24205.invoke(multipart.clj:414)
	at yada.multipart$parse_multipart$this__2646__auto____24204.invoke(multipart.clj:402)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:632)
	at yada.multipart$parse_multipart$this__2646__auto____24204$fn__24232.invoke(multipart.clj:402)
	at manifold.deferred.Listener.onSuccess(deferred.clj:219)
	at manifold.deferred.Deferred$fn__2357$fn__2358.invoke(deferred.clj:396)
	at clojure.lang.AFn.run(AFn.java:22)
	at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)
	at manifold.executor$thread_factory$reify__1758$f__1759.invoke(executor.clj:36)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by malcolmsparks** [comment] 2016-03-12 10:18
Hi Mike - thanks for raising this issue and with your instructions to reproduce which were easy to follow.

Following your instructions, I couldn't repeat the issue my Linux system on the current 1.1.0 version, but we did find a bug in the multipart code last week which I fixed prior to the release. For this reason, __could you confirm the version you're using__, just to rule that out.


```
[malcolm@tulkas ~]$ curl -vi -F file=@file.txt http://localhost:8090/upload/form
*   Trying ::1...
* Connected to localhost (::1) port 8090 (#0)
> POST /upload/form HTTP/1.1
> Host: localhost:8090
> User-Agent: curl/7.47.1
> Accept: */*
> Content-Length: 1049786
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------66fa0b32257bdbb5
> 
< HTTP/1.1 100 Continue
HTTP/1.1 100 Continue

< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Content-Length: 0
Content-Length: 0
< Server: Aleph/0.4.1
Server: Aleph/0.4.1
< Connection: Keep-Alive
Connection: Keep-Alive
< Date: Sat, 12 Mar 2016 10:17:23 GMT
Date: Sat, 12 Mar 2016 10:17:23 GMT

< 
* Connection #0 to host localhost left intact
```

I'll have access to a Mac over the next few days so if this is a Mac-only issue I should be able to reproduce it and find the problem.

Regards,

Malcolm

**Comment by mfikes** [comment] 2016-03-12 16:47
Hi @malcolmsparks, thanks for the quick reply.

I am able to additionally repro on Linux.

In terms of the version I'm using, I initially cloned master (as of yesterday), but I can also reproduce it on both OS X and Linux with a minimal `lein new foo` and by adding `[aleph "0.4.1-beta5"]`, `[bidi "2.0.1"]`, and `[yada "1.1.0"]` to the `project.clj` `:dependencies` vector, and otherwise running the test the same way using the REPL as described in the initial issue description.

For Linux, I repro'd it using an Ubuntu virtual box where I set it up to use Oracle's Java 8. Here are some details of that machine:

```
vagrant@vagrant-ubuntu-trusty-64:~$ uname -a
Linux vagrant-ubuntu-trusty-64 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
vagrant@vagrant-ubuntu-trusty-64:~$ java -version
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)
```

As a debugging aid, I can add some additional info:
* If you add some `println` output for the `Partial` `continue` function, you will see that the NPE happens after a random number of calls to `continue`.
* I have found that sometimes it doesn't fail with an NPE, but appears to lock up (perhaps a different issue entirely).
* I have tried using cURL's `--limit-rate` option to slow things down and it still occurs.
* If I connect with `jconsole` and have things being transferred slowly via `--limit-rate`, having `jconsole` request a GC _seems_ to either get it to lock up or NPE quicker.

> As an aside, I'm working on my own implementations of the `Partial` and `PartConsumer` so that I can stream large files to storage, so memory exhaustion won't be an issue for me. I've also bypassed the current inability to set `:options`, by setting up my own `defmethod request-body/process-request-body "multipart/form-data"` that `assoc-in`'s `[:options :part-consumer]` and then delegates to the original `defmethod`.

**Comment by malcolmsparks** [comment] 2016-03-12 23:13
Hi Mike,

I've just noticed something about your set up - it appears you aren't setting aleph's `raw-stream?` option to true. This is entirely my fault - I haven't made that clear in the documentation (and have corrected this now). We've had some upload issues of this nature before which are all fixed by setting aleph's raw-stream? option. Sometime during my work to move towards a completely async server I switched to using netty's bytebufs exclusively (yada takes care of the reference counting) and the documentation fell behind.

To ensure future users don't misconfigure their aleph servers I'm encourage use of the wrapper I've created in yada.aleph:

```clojure
(defn listener
  "Start an HTTP listener on a given port. If not specified, listener
  will be started on any available port. Returns {:port port :close fn}"
  [routes & [{:keys [port] :or {port 0} :as aleph-options}]]
  (let [server
        (http/start-server
         (as-handler routes)
         (merge {:port (or port 0) :raw-stream? true}
                aleph-options))]
    {:port (aleph.netty/port server)
     :close (fn [] (.close server))}))
```

I'm also working on supporting a wider range of servers (under manifold), the next will be undertow, for which I already have a basic implementation.

Just to confirm, you're right in your approach to extend the Partial and PartConsumer protocols with your own implementations - that is the intended way of implementing the large file streaming you're proposing. I'm keen to open up that extension properly to avoid code duplication.

Hopefully this fixes your issue, but if not let me know.

**Comment by mfikes** [comment] 2016-03-13 17:21
Fantastic Malcolm! Adding `:raw-stream? true` does indeed fix things for me. (I confirmed downstream in my project.) Additionally—(to my initial thinking, at least)—it appears to be correct to have this enabled in our downstream project as we are keen on making it avoid thread use where possible.

I'll leave it to you to decide when this ticket is closed.

**Closed** 2016-03-20 21:34 UTC
