### ISSUE TITLE
yada.aleph/listener should return wait-for-close

### ISSUE THREAD

**Issue by Frozenlock** [juxt/yada#115] opened 2016-08-12 00:19 UTC
While `yada.aleph/listener` already returns a closing function and the port via `:close` and `:port`, one should still be able to either get their hands on the `server` object, or a `:wait-for-close` function.

`wait-for-close` is necessary to prevent the jar from silently exiting.
(See https://github.com/ztellman/aleph/issues/265)

**Comment by malcolmsparks** [comment] 2016-08-12 06:48
In ztellman/aleph#265 @ztellman says that wait-for-close is an implementation detail and I feel we shouldn't publicly expose it (risking breakages in future releases of aleph). It seems the problem is fixed in 0.4.2, and in the meantime `yada.aleph/listener` can be implemented directly by those affected by this issue. What I mean by that is that `yada.aleph/listener` is merely a convenience wrapper around the usually aleph start up code which I added to ensure that `raw-streams?` was set. 

What do you think? I'll keep this issue open while we discuss.

**Comment by Frozenlock** [comment] 2016-08-12 06:56
What I understood reading the issue was that `.wait-for-close` was the implementation detail, while the function `wait-for-close` was for the user.

As said in this [comment](https://github.com/ztellman/aleph/issues/265#issuecomment-237667643)
>(...) I apologize for the unexpected change here, but the new approach is to use `wait-for-close`.

If `:wait-for-close` is not available, perhaps just a `:server` to get a hand of the server object?

For what it's worth, I did like you said and implemented `listener`.

**Closed** 2016-08-12 07:47 UTC

**Comment by malcolmsparks** [comment] 2016-08-12 13:24
You're right. I misunderstood that point, thanks for putting me straight.
