### ISSUE TITLE
Direct memory exhaustion large multipart upload

### ISSUE THREAD

**Issue by mfikes** [juxt/yada#75] opened 2016-03-18 02:19 UTC
If you do a large multipart upload with your own `Partial` and `PartConsumer` implementations (which could stream to storage, but instead simply discard the uploaded data), then the system will exhaust direct memory within a few minutes.

To reproduce, first do `lein new foo` to create a blank project and add the following to the `:dependencies` vector in `project.clj`:

```
[aleph "0.4.1-beta5"]
[bidi "2.0.1"]
[yada "1.1.2"]
```

then, start a REPL in that project and issue the following forms in the REPL:

```
(require '[aleph.http :refer [start-server]]
         '[yada.yada :refer [resource]]
         '[yada.aleph :refer [listener]]
         '[yada.request-body :as request-body])

(import (yada.multipart Partial PartConsumer))

(defrecord MyPartial []
  Partial
  (continue [this _] (prn (java.util.Date.)) this)
  (complete [_ state _] state))

(defrecord MyPartConsumer []
  PartConsumer
  (consume-part [_ _ _])
  (start-partial [_ _] (->MyPartial))
  (part-coercion-matcher [_] {}))

;; Hook in our own part consumer
(let [original-impl (get-method request-body/process-request-body "multipart/form-data")]
  (defmethod request-body/process-request-body "multipart/form-data"
    [ctx body-stream media-type & args]
    (let [new-ctx (assoc-in ctx [:options :part-consumer] (->MyPartConsumer))]
      (apply original-impl new-ctx body-stream media-type args))))

(listener
  ["/upload"
   (resource
     {:methods
      {:post
       {:consumes "multipart/form-data"
        :response (constantly nil)}}})]
  {:port 3000})
```

(Note that the `process-request-body` multimethod is modified in lieu of `:options` setting.)

Now, make a large file:

```
dd if=/dev/zero of=file.txt count=10240000 bs=1024
```

and upload it to the server started in the REPL:

```
curl -F file=@file.txt http://localhost:3000/upload
```

Timestamps will be displayed in the REPL as chunks come in:

```
#inst "2016-03-18T02:03:40.141-00:00"
#inst "2016-03-18T02:03:40.188-00:00"
```

after a few minutes things will fail. On Linux, the exception will look like the following:

```
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 3653632 bytes for committing reserved memory.
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000ff815000, 3653632, 0) failed; error='Cannot allocate memory' (errno=12)
# An error report file with more information is saved as:
# /home/vagrant/yada-dm/hs_err_pid3621.log
Exception in thread "Thread-3" clojure.lang.ExceptionInfo: Subprocess failed {:exit-code 1}
	at clojure.core$ex_info.invokeStatic(core.clj:4617)
	at clojure.core$ex_info.invoke(core.clj:4617)
	at leiningen.core.eval$fn__5625.invokeStatic(eval.clj:271)
	at leiningen.core.eval$fn__5625.invoke(eval.clj:267)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at leiningen.core.eval$eval_in_project.invokeStatic(eval.clj:373)
	at leiningen.core.eval$eval_in_project.invoke(eval.clj:363)
	at leiningen.repl$server$fn__11767.invoke(repl.clj:243)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:650)
	at clojure.core$bound_fn_STAR_$fn__4671.doInvoke(core.clj:1911)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:745)

SocketException The transport's socket appears to have lost its connection to the nREPL server
	clojure.tools.nrepl.transport/bencode/fn--10128/fn--10129 (transport.clj:95)
	clojure.tools.nrepl.transport/bencode/fn--10128 (transport.clj:95)
	clojure.tools.nrepl.transport/fn-transport/fn--10100 (transport.clj:42)
	clojure.core/binding-conveyor-fn/fn--4676 (core.clj:1938)
	java.util.concurrent.FutureTask.run (FutureTask.java:266)
	java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
	java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
	java.lang.Thread.run (Thread.java:745)
```

And on OS X you will see:

```
Mar 17, 2016 6:46:51 PM clojure.tools.logging$eval420$fn__424 invoke
WARNING: error in HTTP server
java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:693)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:645)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:229)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:213)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:133)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:262)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:170)
	at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:131)
	at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:73)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:111)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by malcolmsparks** [comment] 2016-03-18 08:24
Thanks Mike. I have seen the `java.lang.OutOfMemoryError: Direct buffer memory` on Linux too recently. I did some investigation by printing out the refCnt on each buffer and it seemed a little strange - buffers had high refCnt values (e.g. 5 or 6) which would often descend monotonically. I can replicate the bug in much the same way, by steaming a local large file.

My current approach to this is to consider the bug is either in yada (__bY__), manifold (__bM__), aleph (__bA__) or netty (__bN__).

It could be in bY, but the issue also manifests itself outside of multipart (iirc), since I've seen the same thing with large files streaming directly to a temp dir, with no multipart involved. The only code in yada involved here is minimal. See https://github.com/juxt/yada/blob/master/dev/src/yada/dev/upload.clj which adds a :consumer which yada calls directly with the stream of Netty ByfeBuf instances it gets from Aleph. So I'm not sure how the bug could be in yada. 

At this stage I'd like to reach out to @ztellman for any wisdom he can impart but since this is OSS I can't exactly escalate this through management ;)

So let's assume it's a bug in manifold, aleph or netty. In order to discount manifold I'm working on a replacement for aleph and netty (undertow and xnio) on the undertow branch. This is nearly done and should point to whether it's bM or (bA or bN). In any case, it should be relatively straight-forward to create a failing test for manifold+aleph to present to Zach. Or he might indicate that yada is not calling manifold correctly.

I will prioritise this issue for work over the Easter break.

**Comment by malcolmsparks** [comment] 2016-03-18 08:28
Also see https://github.com/ztellman/aleph/issues/214

**Comment by malcolmsparks** [comment] 2016-03-18 09:13
I have raised https://github.com/ztellman/aleph/issues/224 and will follow up in due course with a smaller failing test that doesn't involve yada. @mfikes thanks for this and sorry I haven't got a better answer for you yet.

**Comment by mfikes** [comment] 2016-03-18 15:10
Thanks @malcolmsparks. I appreciate your help!

**Comment by ztellman** [comment] 2016-03-18 17:16
Can you try ` -Dio.netty.allocator.numDirectArenas=0` as a JVM flag, and see if the issue disappears?

**Comment by mfikes** [comment] 2016-03-18 17:42
@ztellman Yes, I can confirm that that JVM flag causes the issue to disappear. (I tried it on OS X.)

**Comment by ztellman** [comment] 2016-03-18 17:47
Interestingly, I've seen that exact error on OS X, but never on Linux.  I've used that flag to work around it on my dev box.  Honestly, I never dug into it too much, because it didn't affect production.  You might try `-XX:MaxDirectMemorySize=1g` (or whatever is appropriate for your machine) and see what happens.  If it doesn't, it might be worth talking to the Netty folks and see if there's an official workaround.

**Comment by malcolmsparks** [comment] 2016-03-18 17:49
I have some failing tests that I'll try over the weekend which stress the
stack quite hard. I'll report on Sunday.


Malcolm Sparks
Director

Email: malcolm@juxt.pro
Web: https://juxt.pro

JUXT LTD.
Software Consulting, Delivery, Training

**Comment by malcolmsparks** [comment] 2016-03-18 17:50
I've tried the MaxDirectMemorySize=1g before, it doesn't help (or at least,
it only delays the problem)


Malcolm Sparks
Director

Email: malcolm@juxt.pro
Web: https://juxt.pro

JUXT LTD.
Software Consulting, Delivery, Training

**Comment by ztellman** [comment] 2016-03-18 17:50
And just to be clear, I've seen this issue with a vanilla Java Netty application, so I'm fairly sure the issue is not with the Clojure elements of the stack.

**Comment by malcolmsparks** [comment] 2016-03-18 17:51
That's good to know. Zach, thanks for your help here - netty still feels a bit like the 'dark arts' to me.

**Comment by ztellman** [comment] 2016-03-18 17:52
When you do your tests, you should add `(aleph.netty/leak-detector-level! :paranoid)` and see what sort of "I got GCed before my reference count went to zero" warnings you get.

**Comment by d-t-w** [comment] 2016-08-12 03:03
I found this issue while working through [my own unrelated problem with netty direct buffer pooling](https://github.com/d-t-w/netty-buffers/). 

I don't use yada, and have only a passing familiarity with aleph, but I have been using clojure and netty for years so thought I might chip in some info.

My first observation is that the issue is intermittent. Sometimes memory usage would blow out almost immediately, sometimes after a minute or two of execution, and sometimes the message would be received fully with zero issue.

My second observation is that message consumption is very slow. Consuming a 1GB file fully takes about 10 minutes. In comparison a simple netty server with only the HTTP codec that drops all chunks on the floor will receive that same 1GB file in about 3 seconds.

Thirdly, I tried briefly reproducing this error with the latest versions of bidi/yada/aleph and all three trial runs completed without issue. Maybe I was lucky, or maybe this error has been scrubbed out somewhere recently.

*Diagnosing*:

There is some background info on Netty buffer pooling in my link above.

If we start a new REPL we will have the default max direct memory of 2GB, that results in 16 Pool Arenas with, to begin with, zero PoolChunks each.

```clojure
(.directArenas (PooledByteBufAllocator/DEFAULT))
=>
[#object[io.netty.buffer.PoolArena$DirectArena
         0x157c4c39
         "Chunk(s) at 0~25%:
          none
          Chunk(s) at 0~50%:
          none
          Chunk(s) at 25~75%:
          none
          Chunk(s) at 50~100%:
          none
          Chunk(s) at 75~100%:
          none
          Chunk(s) at 100%:
          none
          tiny subpages:
          small subpages:
          "]
 #object[io.netty.buffer.PoolArena$DirectArena
         0x45cbb12c
         "Chunk(s) at 0~25%:
          none
          Chunk(s) at 0~50%:
          none
          Chunk(s) at 25~75%:
          none
          Chunk(s) at 50~100%:
          none
          Chunk(s) at 75~100%:
          none
          Chunk(s) at 100%:
          none
          tiny subpages:
          small subpages:
          "]
...
...
```

At this point it's also a good idea to fire up jvisualvm with the Buffer Pools plugin.

We expect netty to allocate all the memory required for a single message to a single arena, since there's a event-loop thread -> pool arena ThreadLocal cache, so one event-loop thread always uses the same arena.

We also expect that we will likely only allocate a single 16MB (default) PoolChunk to that arena, since Netty caches buffers in the same ThreadLocal cache, and we intend to receive a chunk, drop it, release it, receive another chunk, etc. We should only really use a single ByteBuffer (and this is the behaviour we see with a bare Netty server with HttpServerCodec dropping all messages).

If I then start a 1GB upload I see my direct memory usage (via visualvm) jump to 16MB as the PoolChunk is allocated, and for quite some time (several minutes generally) this remains the case. At any point we can check the state of the PoolArenas, and we see a single arena with a single chunk, with a small amount of memory allocated (basically enough for one 64k buffer and a couple smaller).

```clojure
(.directArenas (PooledByteBufAllocator/DEFAULT))
=>
[#object[io.netty.buffer.PoolArena$DirectArena
         0x31bd8884
         "Chunk(s) at 0~25%:
          Chunk(46d7fd67: 1%, 114688/16777216)
          Chunk(s) at 0~50%:
          none
          Chunk(s) at 25~75%:
          none
          Chunk(s) at 50~100%:
          none
          Chunk(s) at 75~100%:
          none
          Chunk(s) at 100%:
          none
          tiny subpages:
          16: (2049: 1/32, offset: 8192, length: 8192, elemSize: 256)
          small subpages:
          1: (2051: 1/8, offset: 24576, length: 8192, elemSize: 1024)
          "]
```

Now, at some point the issue occurs, and all of the remaining message is read immediately into memory within a second or so.

I've no idea what causes this, but effectively it looks as if each remaining chunk in the message is read by netty, allocated to a bytebuffer, and that buffer is not released, the next chunk being read and allocated, and so on. Remember netty is capable of performing that read for the entire 1GB in about 3s. This allocation without release is the large vertical spike in the image below.

![image](https://cloud.githubusercontent.com/assets/2832467/17611529/7ffe1994-608b-11e6-8b8d-476b07ff0cee.png)

Can also be seen by inspecting the PoolArena directly, we see a slew of allocated PoolChunk:

```clojure
(.directArenas (PooledByteBufAllocator/DEFAULT))
=>
[#object[io.netty.buffer.PoolArena$DirectArena
         0x19bda70e
         "Chunk(s) at 0~25%:
          Chunk(81c0942: 5%, 688128/16777216)
          Chunk(s) at 0~50%:
          none
          Chunk(s) at 25~75%:
          none
          Chunk(s) at 50~100%:
          Chunk(21913aed: 54%, 9027584/16777216)
          Chunk(44bc617a: 99%, 16760832/16777216)
          Chunk(s) at 75~100%:
          Chunk(3e5b6a9d: 99%, 16760832/16777216)
          Chunk(s) at 100%:
          Chunk(56e5320d: 100%, 16777216/16777216)
          Chunk(7e8b2c6e: 100%, 16777216/16777216)
          Chunk(599b2574: 100%, 16777216/16777216)
          Chunk(3cf1b358: 100%, 16777216/16777216)
          Chunk(43fb8b91: 100%, 16777216/16777216)
          Chunk(643427dc: 100%, 16777216/16777216)
          Chunk(64840eab: 100%, 16777216/16777216)
          Chunk(55de0a10: 100%, 16777216/16777216)
          Chunk(4a66b439: 100%, 16777216/16777216)
          Chunk(f29606e: 100%, 16777216/16777216)
          Chunk(4b1cd676: 100%, 16777216/16777216)
          Chunk(6eb7db8f: 100%, 16777216/16777216)
          Chunk(118f6d1c: 100%, 16777216/16777216)
          Chunk(55614553: 100%, 16777216/16777216)
          Chunk(786386ef: 100%, 16777216/16777216)
          Chunk(28d851cf: 100%, 16777216/16777216)
          Chunk(42d53e45: 100%, 16777216/16777216)
          Chunk(1dc1b091: 100%, 16777216/16777216)
          Chunk(79710938: 100%, 16777216/16777216)
          Chunk(13cd79f0: 100%, 16777216/16777216)
...
...
...
```

At this point if you have sent a file > max direct memory size you will see an OOM. 

In this test case I have sent a 1GB file (somehow corresponds to almost 2GB memory usage, not entirely sure how that's doubled up - is @ztellman 's byte-streams smart enough to convert a direct ByteBuf to a direct ByteBuffer?).

Anyway, since I have already processed some small amount of the message (pre-spike), I can fit the remaining amount in memory. You'll see from the image above that the yada listener continues to consume these allocated bytebuffer, unaware that any one-by-one message-chunk execution has been overwhelmed and the entire message read entirely into memory. It will complete successfully within about ten minutes.

Hope some of this has been of use. As I said I'm not sure if this issue persists since I couldn't reproduce with latest versions, if it does then you have some more info to go forward with.

**Comment by malcolmsparks** [comment] 2016-08-12 07:53
@d-t-w, many thanks for this very thorough write-up. Your description of the problems concur with what I was seeing when testing with large files, and I failed in my attempt to get to the cause of the issue. Since then some dependencies have changed but I still have the original file-upload code and some large files that I can test with, to see if the issue remains.

**Comment by d-t-w** [comment] 2016-08-13 00:57
No problem @malcolmsparks, if you find the issue persists and you want help isolating the issue to netty or beyond just ping me - happy to look at it further, was just passing yesterday.

**Comment by malcolmsparks** [comment] 2016-08-13 12:44
I've done some testing with some large 4Gb files today. 

With the current yada master 3963d267a65114a4f618413c668ea1c187c1eef0, which uses aleph 0.1.4 I am not seeing the issue any more, either with or without `-Dio.netty.allocator.numDirectArenas=0`.

![heap](https://cloud.githubusercontent.com/assets/163131/17643227/42bc2208-615b-11e6-8dd9-6ffd59acf046.png)

I'm only seeing about 10MBps throughput, however, but that may be because I'm writing the file. I've seen yada stream an upload at about 1GBps before, so I need to keep investigating. However, at least it's reliably working now, even if performance could be improved.

**Comment by malcolmsparks** [comment] 2016-08-13 12:58
Ah, I discovered I was still printing out to the console on every buffer. Now I've removed that I'm up to about 80MB/s. I'm streaming a 4Gb file, without chunked transfer encoding, and writing it to an NVMe SSD disk. I can stream the whole file this way in 52 seconds. For comparison, a `cp` manages the same thing in 7 secs on my system, so yada seems pretty fast now.

**Comment by malcolmsparks** [comment] 2016-08-13 13:53
Closing as per above comments.

**Closed by malcolmsparks** 2016-08-13 13:53 UTC
